### PR TITLE
add i18n support

### PR DESCRIPTION
**Pull request by tgfjt**
Hi! @finnp 

This PR is for i18n support:smile: with [workshopper-adventure](https://github.com/workshopper/workshopper-adventure).
also I added `verify.js` instead of `adventure-verify`, because it doesn't tap logs so I added this line. https://github.com/tgfjt/test-anything/blob/workshopper-adventure/verify.js#L58

### CODE REVIEW

**Comment by tgfjt** [comment]
For examples, we need these files in case of Japanese Translation:

* `i18n/ja.json`
* `exercise/xxx/instruction_ja.md`
* `exercise/log-it-out/messages_ja.json`

_but I've not translated yet!_

**Comment by finnp** [comment]
Thanks a lot for taking the time to do this! 

I am not sure about that verify fix though. Seems to me like it is a bug in `workshopper-adventure`. @martinheidegger What do you think? The result of verify should be piped to stdout automaticcaly by `workshopper-adventure`.

**Comment by tgfjt** [comment]
It's not only piping but also logging `[object object]`.
I've read the code but I don't understand compatibily for other workshopper...

**Comment by martinheidegger** [comment]
I didn't implement streaming yet (I knew i forgot something!), it has to have an API change [here]( https://github.com/workshopper/workshopper-adventure/blob/6d6dcd770796e1798a1fb7c0b34b1c9dee02aeff/lib/print.js#L16) and some additions in [here](https://github.com/workshopper/workshopper-adventure/blob/e3e269ee44759357f394ceaa8beb9b51fc869128/adventure.js#L236) and at a few other places.

Btw.: I am in the process of refactoring the workshopper: https://github.com/workshopper/workshopper-adventure/tree/refactoring to make it better readable.

**Comment by tgfjt** [comment]
Thanks, I see.. This request might be too hurry :wink:
I'll try something to support streaming.

**Comment by tgfjt** [comment]
@finnp 
Hi! I think that it's finally done. 
(Great @martinheidegger wrote it almost.:smile: )

Would you review it?

Thanks.

**Pull request closed without merging**
